scripts/determine-and-publish-git-tag.sh

This fixes an issue where the Go Module Proxy doesn't like Minor or Patch versions to start with a `0`, returning:
> bad request: version "v0.20220622.050833" is not canonical (wanted "")
Whilst not ideal, a `1` is at least consistent (rather than switching to use 12h time, where these would be of differing lengths)

tooling: updating the Patch version of the Git Tag to be prefixed by a `1`

---

sdk/client/options.go
sdk/client/resourcemanager/poller_provisioning_state.go
sdk/internal/metadata/client_test.go
sdk/odata/query.go

- Metadata client tests to run only as needed, similar to auth tests
- Refactor OData and Client types for easier re-use

Test fix and OData tweaks

---

go.mod
go.sum
sdk/auth/client_certificate_authorizer.go

golang.org/x/crypto/pkcs12 is unmaintained, this replacement is license compatible and more up-to-date.
This wins us the following:
- Support for parsing out certificate chains stored in PKCS#12 bundles
- Support for SHA256 HMAC which is the default hash function for PKCS#12 bundles with newer versions of OpenSSL/LibreSSL
Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/19374
Related: https://github.com/manicminer/hamilton/pull/212

Switch PKCS#12 library to software.sslmate.com/src/go-pkcs12

---

.github/workflows/automation-open-pull-request.yaml
scripts/open-pull-request.sh

This PR updates the 'open-pull-request' job to launch a bash script with an explicit exit code, rather than erroring directly

tooling: updating the open pr script to run via bash

---

sdk/client/resourcemanager/poller.go
sdk/client/resourcemanager/poller_delete.go
sdk/client/resourcemanager/poller_lro.go
sdk/client/resourcemanager/poller_provisioning_state.go

This PR fixes a number of issues identified when enabling the base layer in https://github.com/hashicorp/terraform-provider-azurerm/pull/20688, namely:
1. Some Resource Manager APIs return the LRO OperationStatus URI on a verbose hostname (including the port), such that the check we have present here isn't strictly needed (else we fail comparing `https://management.azure.com` to `https://management.azure.com:443`, which whilst technically the same the LRO URI isn't guaranteed to be on the same port afaik)
2. Some Resource Manager APIs (such as SignalR) return an LRO Status of `Running` rather than `InProgress`, as such this PR adds an exception for this
3. Introduces a Delete LRO - which (after deleting a resource) will validate that the resource ultimately disappears

SDK: updating the  pollers for `resourcemanager`

---

go.mod
go.sum

Exposes the `KeyVault` and `KeyVaultKey` Common IDs

dependencies: updating to `v0.53.0` of `github.com/hashicorp/go-azure-helpers`

---

go.mod
go.sum

Resolves https://github.com/hashicorp/pandora/pull/2183/files#r1122986709
Related: https://github.com/hashicorp/pandora/pull/2186

dependencies: updating to `v0.54.0` of `github.com/hashicorp/go-azure-helpers`

---

sdk/auth/azure_cli_authorizer.go
sdk/auth/shared_key_authorizer.go

Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/20674
Fixes a bug when authenticating via Azure CLI in Cloud Shell.
**Testing**

Bugfix: skip auxiliary tokens for CLI auth instead of erroring

---

sdk/client/resourcemanager/poller.go
sdk/client/resourcemanager/poller_lro.go

Accounting for some behavioural issues spotted in https://github.com/hashicorp/terraform-provider-azurerm/pull/20810

resourcemanager/poller: splitting Delete and non-Delete LROs

---

sdk/auth/cached_authorizer.go
sdk/auth/client_credentials.go
sdk/auth/token.go
sdk/claims/claims.go

The default method `*oauth2.Token{}.Valid()` has a hardcoded delta of 10 seconds, which means that tokens are only renewed 10 seconds before they expire. This leads to race conditions during long running operations with the Resource Manager API, when a polling request is built immediately prior to this window, but only sent on or after the expiry time. Additionally, it's plausible that 1 (or more) second(s) may be lost during the process of token issuance, since it's likely the token is generated prior to being returned by the API, and it is the latter that informs us of the expiry time.
This change extends this window to 10 minutes for any access token with a validity period of 20+ minutes. For tokens having a validity period less than 20 minutes, those are renewed when 50% or more of …

auth: Use a custom function to determine access token expiry

---

sdk/auth/client.go
sdk/auth/client_credentials.go
sdk/auth/github_oidc_authorizer.go
sdk/auth/managed_identity_authorizer.go

Docs: https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/resilience-client-app
Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/20901

auth: use a retryable http client to handle 429 responses from token endpoint(s)

---

sdk/environments/scopes.go

Allow inlined Apis such as App Configuration Data Plane to obtain an auth token with MSI auth
related with https://github.com/hashicorp/terraform-provider-azurerm/issues/20835 and https://github.com/hashicorp/go-azure-sdk/pull/320
test:
```hcl
adminuser@example-machine:~/test$ cat main.tf
terraform {
required_providers {
azurerm = {
source = "hashicorp/azurerm"
}
}
}
provider "azurerm" {
features {}
tenant_id       = "xxx"
subscription_id = "xxx"
use_msi         = true
}
resource "azurerm_resource_group" "example" {
name     = "appconf-example-resources"
location = "West Europe"
}
resource "azurerm_app_configuration" "appconf" {
name                = "wttestappConf1"
resource_group_name = azurerm_resource_group.example.name
location            = azurerm_resource_group.example.location
} …
```

sdk/environments: obtaining the resource from the endpoint if a resourceIdentifier isn't present

---

sdk/environments/azure_public.go
sdk/environments/helpers.go

needed by Data plan SDK of Attestation(only support in "East US 2", "West Central US" & "UK South" ).

`enviroments`: add `Attestation` api endpoint

---

sdk/auth/client.go
sdk/auth/managed_identity_authorizer.go

The `http.Client{}.Timeout` field applies to all retried requests, since they all occur during the course of a single client request.
Per `net/http`, when the `Timeout` field is zero, it will have no effect and the request context has precedent:
```go
// Timeout specifies a time limit for requests made by this
// Client. The timeout includes connection time, any
// redirects, and reading the response body. The timer remains
// running after Get, Head, Post, or Do return and will
// interrupt reading of the Response.Body.
//
// A Timeout of zero means no timeout.
//
// The Client cancels requests to the underlying Transport
// as if the Request's Context ended.
//
// For compatibility, the Client will also use the deprecated
// CancelRequest method on Transport if found. New
// …
```

auth: remove client timeout and rely on the request context

---

sdk/auth/client.go

This is to make the log from the client comply with the other provider logs (e.g. eliminating it from showing in the stderr during acctest, stream it to the provider log file path, etc.)

Set  as the auth client's logger

---

sdk/client/client.go

Intentionally ignore errors when parsing OData for unpaged responses - this can fail for various reasons but notably when the JSON response is technically valid but comprises a non-object literal such as a string or int.
We are only parsing OData from the response here in order to pass it along to a provided ValidStatusFunc, and this is a best-effort as the provided *odata.OData may be nil.
Fixes: #381

Bugfix: OData parsing for bad responses

---

sdk/auth/autorest/auth.go
sdk/auth/token.go

also extend token renewal buffer to 20 minutes, so tokens are renewed 20 mins before their expiry (or after 50% of their validity period, whichever is earlier)
e.g.
Token Validity  | Renewed after
--- | ---
60 mins | 40 mins
50 mins | 35 mins
40 mins | 20 mins
30 mins | 15 mins
20 mins | 10 mins
10 mins | 5 mins

auth: fix bad error check

---

sdk/client/resourcemanager/poller_lro.go

`ContainerRegistry` `2019-06-01-preview` API for AgentPool returns `Creating` instead of `InProgress`

base-layer: add `Creating` as a valid status for LRO Poller

---

sdk/client/client.go

Same as #382, but for the retryable client initialized during executing a `Request`. This and the `auth.Client` are the only two places that initialize the retryable client, hence needing this logger setting.

Enable logger for the request retryable client - same as `auth.Client`

---

sdk/client/client.go

Ensure POST with not req body also defined the header `Content-Length`. The motivation of this PR is because I've encountered error from Azure service complaining the POST request has not defined the `Content-Lenght` in header:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```
See: https://github.com/hashicorp/terraform-provider-azurerm/pull/21481 for details.

Ensure POST with not req body also defined the header `Content-Length`

---

sdk/client/client.go

I'm not sure in which case we will make use of the response on a "failed" request. This seems to be an anti-pattern in Go, in which case users should assume the returned `value` is useless/undefined on a non-nil `error`. The only scenario is for error messaging, if that is the case, we can somehow wrap the response message to the `err` itself and return the `err` instead.
The motivation for this PR is that in a specific case that the DNS failed to resolve for the URL, the dail failed error message won't be returned, instead the client returns somethings like following:
```
2023/04/19 14:53:43 executing request: Get "https://mgdpestorageaccountnameg.blob.core.windows.net/": http: RoundTripper implementation (*retryablehttp.RoundTripper) returned a nil *Response with a nil error
exit status …
```

Remove the `ErrorHandler` for the per-request retryable client

---

sdk/client/client.go
sdk/client/client_test.go

This PR adds support for requests and responses containing `[]byte`'s - and also supports for marshaling and unmarshaling bodies containing powershell scripts which are defined as a byte array.
Supersedes #298

client/sdk: support for `[]byte` requests and responses

---

sdk/client/pollers/interface.go
sdk/client/pollers/poller.go
sdk/client/resourcemanager/errors.go
sdk/client/resourcemanager/errors_test.go

This PR lays the foundation for solving a number of issues within `hashicorp/terraform-provider-azurerm` by providing a function which parses the Azure Error from the API Response for both Long Running Operations and regular Resource Manager operations.
There's a considerable number of different formats for error messages, so this isn't going to be necessarily be conclusive, hence falling back to a generic error message showing the API body if we can't parse it.
A random selection of issues this'll ultimately end up fixing:
* https://github.com/hashicorp/terraform-provider-azurerm/issues/1775
* https://github.com/Azure/azure-rest-api-specs/issues/9672
* https://github.com/hashicorp/terraform-provider-azurerm/issues/11491
* https://github.com/hashicorp/terraform-provider-azurerm/issues/1610 …

sdk/client/resourcemanager: parsing error messages from API Responses

---

sdk/client/resourcemanager/poller_lro.go

resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/21870
to change the error mesage to:
```
=== CONT  TestAccAppConfiguration_standard
testcase.go:110: Step 1/2 error: Error running apply: exit status 1
Error: creating Configuration Store (Subscription: "xxx"
Resource Group Name: "acctestRG-appconfig-230522161800054336"
Configuration Store Name: "appConf1"): polling after Create: polling failed: {"id":"/subscriptions/xxx/providers/Microsoft.AppConfiguration/locations/westeurope/operationsStatus/exSCtZucYyDRejH0Qry3U2xmdvGTx3yogpJ1TObVtSQ","name":"exSCtZucYyDRejH0Qry3U2xmdvGTx3yogpJ1TObVtSQ","status":"Failed","error":{"code":"NameUnavailable","message":"The specified name is already in use.","additionalInfo":[{"type":"ActivityId","info":{"activityId":"0ddb9e62-9386-4040 …
```

sdk/client: raising an error when lro operation failed or cancelled

---

go.mod
go.sum
sdk/client/client.go

* dependencies: updating to v0.7.4 of github.com/hashicorp/go-retryablehttp
* remove ineffectual setting of `Content-Length` header
Supercedes: #448

Bugfix: resolve absent `Content-Length` / `Transfer-Encoding` headers for HTTP/2 `PUT` / `POST` requests

---

sdk/auth/client.go
sdk/client/client.go
sdk/internal/metadata/client.go

This is defaulted in Go as of 1.18: https://go.dev/doc/go1.18#tls10 however there's no harm in being explicit

sdk: explicitly setting Min TLS to 1.2

---

sdk/client/client.go
sdk/client/client_test.go

add a unit test to simulate the real sdk behavior in automation sdk, it will panic as below. change to use pointer assignment instead of using reflect. 
https://github.com/hashicorp/go-azure-sdk/blob/e4eafebf7f182d142a29653e55d6865ca39f9bc2/resource-manager/automation/2022-08-08/dscconfiguration/method_getcontent.go#L47-L49
```
panic: reflect: call of reflect.Value.SetBytes on zero Value [recovered]
panic: reflect: call of reflect.Value.SetBytes on zero Value
goroutine 19 [running]:
testing.tRunner.func1.2({0x7115c0, 0xc00012c1e0})
/home/wuxu/.go/.versions/1.19.5/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
/home/wuxu/.go/.versions/1.19.5/src/testing/testing.go:1399 +0x39f
panic({0x7115c0, 0xc00012c1e0})
/home/wuxu/.go/.versions/1.19.5/src/runtime/panic.go:884 +0x212 …
```

`client/sdk`: fix `*[]bytes` response unmarshal may panic when set by reflect

---

sdk/client/msgraph/client.go
sdk/client/msgraph/client_test.go

Ensuring the method arguments are compatible between clients helps to simplify the generators

base client: align msgraph instantiator func with resourcemanager

---

sdk/client/dataplane/storage/client.go

Storage has at least 3 known domain formats depending on the configuration of the Storage Account:
1. `https://{accountname}.{component}.blob.windows.net` - for generic storage accounts
2. `https://{accountname}.{dnszone}.{component}.storage.azure.net` - for storage accounts configured using AzureDNSZone
3. `https://{accountname}.{component}.{edgezone}.edgestorage.azure.net` - for storage accounts configured using an Edge Zone
These will also differ per environment too.
As such by updating the constructor to take the baseUri directly, we avoid issues with this.

sdk/client/dataplane/storage: updating the storage base client to take the baseUri rather than computing it

---

sdk/client/resourcemanager/poller_lro.go

LRO poller: Adding more un-documented pending `status` for storage sync

---

sdk/client/resourcemanager/poller_lro.go

This service returns `Provisioning` instead of `InProgress`:
```
Error: creating Server (Subscription: "*******"
Resource Group Name: "acctestRG-analysis-230731093230507793"
Server Name: "acctestass230731093230507793"): polling after Create: `result.Status` was nil/empty - `op.Status` was "Provisioning" / `op.Properties.ProvisioningState` was ""
```
This PR fixes this test:
```
-run=TestAccAnalysisServicesServer_basic -timeout=60m
=== RUN   TestAccAnalysisServicesServer_basic
=== PAUSE TestAccAnalysisServicesServer_basic
=== CONT  TestAccAnalysisServicesServer_basic
--- PASS: TestAccAnalysisServicesServer_basic (173.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/analysisservices	174.813s
```

resourcemanager/poller: supporting `AnalysisServices`

---

sdk/client/resourcemanager/poller_provisioning_state.go

Both API Management/Schema @ 2021-08-01/2022-08-01 and Automation/DSCConfiguration@2020-01-13-preview support returning both a LRO and an immediate response. In this case since we retrieve the original URI and get a 200 OK /without/ a provisioningState header - we'll special-case this for now.
Fixes https://github.com/hashicorp/go-azure-sdk/issues/542

sdk/client/resourcemanager: support for LROs which also return immediately

---

sdk/client/resourcemanager/errors.go
sdk/client/resourcemanager/errors_test.go

Fixes https://github.com/hashicorp/go-azure-sdk/issues/560

sdk/client/resourcemanager: parsing the error types returned from the PaloAlto API's

---

sdk/client/client.go
sdk/client/resourcemanager/poller_delete.go

Databricks @ 2023-02-01 returns a literal empty string from the initial Delete operation: https://github.com/hashicorp/go-azure-sdk/issues/436

sdk/client: fixing an issue when parsing the OData from the API Response

---

sdk/client/resourcemanager/poller.go
sdk/client/resourcemanager/poller_test.go

Some LROs return a 201 with the Location header as a self-reference, polling on that URI returns a 200 OK with no provisioningState or status field to poll on - as such we need to special-case to handle this.
Fixes an issue in `Automation` @ `2022-08-08` in `DSCNodeConfiguration` / `CreateOrUpdate`
Fixes https://github.com/hashicorp/terraform-provider-azurerm/pull/22781

client/resourcemanager: handling self-referenced LROs

---

sdk/environments/environment.go

Consider an API available if it has an endpoint or a resourceIdentifier (data plane APIs can be initialized with no endpoint)

Environments: consider an API available if it has an endpoint or a resourceIdentifier

---

sdk/client/resourcemanager/poller.go
sdk/client/resourcemanager/poller_provisioning_state.go
sdk/client/resourcemanager/poller_test.go

Most of API Management returns a 202 with a self reference containing an `asynctoken`, as such if a self-reference exists then we can use this URI directly.
Fixes:
```
Error: creating/updating Api (Subscription: "*******"
Resource Group Name: "acctestRG-230803055317928116"
Service Name: "acctestAM-230803055317928116"
Api: "acctestAMA-230803055317928116"): performing CreateOrUpdate: no applicable pollers were found for the response
```
From https://github.com/hashicorp/terraform-provider-azurerm/pull/22783

sdk/client/resourcemanager: supporting 202's with a self reference

---

sdk/client/resourcemanager/poller_lro.go

This is caught by: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_STORAGE/4701?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildChangesSection=true:
```
------- Stdout: -------
=== RUN   TestAccStorageSyncGroup_basic
=== PAUSE TestAccStorageSyncGroup_basic
=== CONT  TestAccStorageSyncGroup_basic
testcase.go:113: Step 1/2 error: Error running apply: exit status 1
Error: creating Storage Sync Service (Subscription: "*******"
Resource Group Name: "acctestRG-SS-230803032141787572"
Storage Sync Service Name: "acctest-StorageSync-230803032141787572"): polling after StorageSyncServicesCreate: `result.Status` was nil/empty - `op.Status` was "newManagedIdentityCredentialStep" / …
```

poller_lro: Adding more intermediate state for storage sync

---

sdk/client/resourcemanager/poller_lro.go

Allows `healthbot` to pass:
```
$ https_proxy=http://localhost:8888 TF_ACC=1 go test -v ./internal/services/bot -run=TestAccBotHealthbot_basic -v -timeout=60m
=== RUN   TestAccBotHealthbot_basic
=== PAUSE TestAccBotHealthbot_basic
=== CONT  TestAccBotHealthbot_basic
--- PASS: TestAccBotHealthbot_basic (137.23s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/bot	138.093s
```

client/resourcemanager: adding `Waiting` as a Provisioning State for HealthBot

---

sdk/client/client.go

The argument for request marshal is `[]byte` not '`*[]byte` (the response is `*[]byte`)
so method below would failed with err: `performing ReplaceContent: internal-error: `payload` must be *[]byte but got [xx xx]`
https://github.com/hashicorp/go-azure-sdk/blob/32fa38105db88915b1a53cc2a590056821989a88/resource-manager/automation/2022-08-08/runbookdraft/method_replacecontent.go#L24-L40

`sdk/client`: req marshal with `[]byte` instead of `*[]byte`

---

go.mod
go.sum

Unblocks https://github.com/hashicorp/pandora/pull/2899

dependencies: updating to `v0.59.0` of `github.com/hashicorp/go-azure-helpers`

---

sdk/client/resourcemanager/poller_lro.go

Since the test `TestAccAzureRMAnalysisServicesServer_suspended` fails with the following errors, I assume that we should add more pending status `Resuming` and `Scaling` for `anaylsisservices`, correct?    
```
Error: starting Server (Subscription: "..."
Resource Group Name: "acctestRG-analysis-230807094726498046"
Server Name: "acctestass230807094726498046"): polling after Resume: `result.Status` was nil/empty - `op.Status` was "Resuming" / `op.Properties.ProvisioningState` was ""
with azurerm_analysis_services_server.test,
on terraform_plugin_test.tf line 26, in resource "azurerm_analysis_services_server" "test":
26: resource "azurerm_analysis_services_server" "test" {
```        
```
Error: updating Server (Subscription: "..."
Resource Group Name: "acctestRG-analysis-230807133137055663" …
```

`poller_lro` : add pending status `Resuming` and `Scaling` for `anaylsisservices`

---

sdk/client/client.go
sdk/client/msgraph/client.go
sdk/client/request_options.go
sdk/client/resourcemanager/client.go

Changing this after coming across this request which doesn't use a content-type: https://learn.microsoft.com/en-us/rest/api/storageservices/get-file

`sdk/client` : allow content-type to not be set

---

sdk/client/resourcemanager/poller_lro.go

test failure:
```
Error: creating Deployment Script (Subscription: "*******"
Resource Group Name: "acctest-rg-230828001033900459"
Deployment Script Name: "acctest-rdsac-230828001033900459"): polling after Create: `result.Status` was nil/empty - `op.Status` was "provisioningResources" / `op.Properties.ProvisioningState` was ""
with azurerm_resource_deployment_script_azure_cli.test,
on terraform_plugin_test.tf line 28, in resource "azurerm_resource_deployment_script_azure_cli" "test":
28: resource "azurerm_resource_deployment_script_azure_cli" "test" {
creating Deployment Script (Subscription:
"*******"
Resource Group Name: "acctest-rg-230828001033900459"
Deployment Script Name: "acctest-rdsac-230828001033900459"): polling after
Create: `result.Status` was nil/empty - `op.Status` was …
```

add lro status exception for DeploymentScripts

---

sdk/client/resourcemanager/errors.go
sdk/client/resourcemanager/errors_test.go

Sometimes the inner message can have more details, meaning we should surface that too. This turns:
```
ValidationError: The request is not valid
```
into:
```
The request is not valid.
Resource name is not valid. It must be between 3 and 26 characters and can only include alphanumeric characters and hyphens.
```
Spotted in DevCenter

sdk/client/resourcemanager: parsing additional details from the azure error responses where possible

---

.github/workflows/automation-release.yaml
.github/workflows/pr-acceptance-tests.yml
.github/workflows/pr-unit-tests.yaml
.github/workflows/pr-validate-go-get.yaml
scripts/update-azurerm-provider.sh

This PR (attempts) to conditionally update the dependency in `hashicorp/terraform-provider-azurerm` whenever a release occurs in this repository, and the release pull request includes `update-azurerm-after-release`. As mentioned in https://github.com/hashicorp/terraform-provider-azurerm/pull/23498, the tool being run determines the changes in the latest SDK release and then attempts to upgrade each of the AzureRM Services to using this version.
This PR also updates the GHA's to pull the Go version from the `.go-version` file - since they weren't before.
There's an intentional sleep in this script since we need to wait for the GHA on the `hashicorp/terraform-provider-azurerm` repository to be run (to open the PR) - ~which also needs to be added before this PR can be merged~ done (~as do …

tooling: support for conditionally updating the AzureRM Provider via a Tag

---

.github/workflows/automation-release.yaml

Right now this is a string, which means these aren't matching

automation: the output value is a literal boolean

---

.github/workflows/automation-release.yaml

This isn't being expanded, so doing this as a workaround

github actions: being explicit with the tag

---

sdk/client/client.go

Seen in the Dalek:
```
2023/10/19 17:10:44 processing Resource Manager: running Subscription Cleaner "Delete Resource Groups in Subscription" in "Subscription (Subscription: \"XXX\")": running Cleaner "Notification Hub Namespaces" for Resource Group (Subscription: "1a6092a6-137e-4025-9a7c-ef77f76f2c02"
19:10:44   Resource Group Name: "acctestRG-231016095632111930"): deleting Namespace (Subscription: "XXX"
19:10:44   Resource Group Name: "acctestRG-231016095632111930"
19:10:44   Namespace Name: "acctestnhn-231016095632111930"): performing Delete: unexpected status 408 with error: RequestTimeout:
```

sdk/client: auto-retrying when a 408 is returned

---

.github/workflows/automation-release.yaml

This is required in order to obtain the diff between the previous tag and current tag during the release/when updating the AzureRM Provider

automation: checking out the full history for the release step

---

.github/workflows/pr-labeler.yaml

to avoid removing `release-once-merged` label, works around https://github.com/actions/labeler/issues/624

tooling: run labeler once per PR

---

sdk/client/resourcemanager/poller_lro.go

While creating SAP Virtual Instance, there is an intermediate state "Preparing System Configuration".

poller_lro : add pending status "Preparing System Configuration" for SAPVirtualInstance

---

sdk/client/resourcemanager/poller_lro.go

While authorizing the replication connection on the source netapp volume, there is an intermediate state "AuthorizeReplication".
While breaking the replication connection on the source netapp volume, there is an intermediate state "BreakReplication".
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/23717

poller_lro : add pending status AuthorizeReplication and BreakReplication for NetAppVolumeReplication

---

go.mod
go.sum

First part of unblocking https://github.com/hashicorp/terraform-provider-azurerm/pull/23721

dependencies: updating to `v0.63.0` of `github.com/hashicorp/go-azure-helpers`

---

sdk/environments/azure_china.go
sdk/environments/azure_gov.go
sdk/environments/azure_public.go
sdk/environments/helpers.go

Needed for: https://github.com/hashicorp/terraform-provider-azurerm/pull/23789

Add App Configuration to environment

---

.github/workflows/automation-release.yaml

Polling once every 15s, for a maximum of 20 times - to allow for the PR to be opened in the background

automation: updating the polling interval

---

.github/workflows/automation-release.yaml

This means we'll only attempt to push a branch/poll for the PR/post a comment when there's differences between the current branch and `main`

automation: conditionally pushing the branch/polling for the PR/posting a comment only when changes exist

---

go.mod
go.sum

Enables https://github.com/hashicorp/pandora/pull/3400

dependencies: updating to `v0.64.0` of `github.com/hashicorp/go-azure-helpers`

---

sdk/environments/helpers.go

Correctly set the `resourceIdentifier` for control plane APIs such as Resource Manager and MS Graph.
`resourceIdentifier` is used for constructing scopes for access tokens, this change ensures that the correct base URI for an API is used in custom cloud environments (and may also fix similar issues with Azure China).
Ref: https://github.com/hashicorp/terraform-provider-azurerm/issues/22495#issuecomment-1808943935

environments: correctly set the resourceIdentifier

---

go.mod
go.sum

Unblocks https://github.com/hashicorp/pandora/pull/3271

dependencies: updating to `v0.65.0` of `github.com/hashicorp/go-azure-helpers`

---

sdk/environments/azure_china.go

Storage in china actually uses `https://storage.azure.com` as identifier URI, not `https://core.chinacloudapi.cn`

environments: fix identifier URI for storage in china

---

scripts/update-azurerm-provider.sh

This file is used to output the variable for whether there's changes to push or not, but since we're outputting this into a variable elsewhere, we can just output this as the value and not a key/value pair here.

automation: outputting the value and not the key/value into the automation file

---

.github/workflows/pr-labeler.yaml

V5 requires config changes and wants to be done everywhere at once

github: downgrading to `actions/labeller@v4` for now

---

go.mod
go.sum

Dependency for https://github.com/hashicorp/pandora/pull/3609

dependencies: updating to `v0.65.1` of `github.com/hashicorp/go-azure-helpers`

---

.github/workflows/automation-release.yaml
scripts/determine-git-tag.sh
scripts/publish-git-tag.sh

This is needed as a part of https://github.com/hashicorp/pandora/issues/3601 since we're going to be publishing multiple Go Modules at different paths - but the version number of each of them is going to be the same.
As such this PR splits the determining and publishing of the Git Tag - such that the existing update tooling continues to work with minor changes (tracked in https://github.com/hashicorp/terraform-provider-azurerm/pull/24602).
Given this is a Github Action this is hard to test locally - I've tested the scripts (which are fine) - but I suspect this change should be fine to merge today, prior to enabling module support.

automation: splitting the determining and publishing of the Git Tag

---

.github/workflows/automation-release.yaml
scripts/publish-git-tag.sh

Using `go get` on the SDK module means that we can end up unintentionally downgrading, since we're sure the SDK Version
exists (since we've just published it) - `sed` ensures this value will be what we're expecting.

automation: updating the go module update to use sed

---

.github/labeler.yml

Minor nit, but ensures that `release-once-merged` is added for all the Auto PRs

tooling: updating the labeller to add `release-once-merged` for both `microsoft-graph` and `sdk`

---

sdk/client/resourcemanager/poller_lro.go

This PR is to fix the issue caused by upgrading fabric managed service sdk to new base layer: https://github.com/hashicorp/terraform-provider-azurerm/pull/24654#issuecomment-1918502177. 
Acctest failure message:
```
testcase.go:113: Step 5/5 error: Error running apply: exit status 1
Error: adding/updating Node Type (Subscription: "*******"
Resource Group Name: "acctestRG-sfmc-240131010138563091"
Managed Cluster Name: "testacc-sfmc-xyszh"
Node Type Name: "test1"): polling after CreateOrUpdate: `result.Status` was nil/empty - `op.Status` was "Created" / `op.Properties.ProvisioningState` was ""
with azurerm_service_fabric_managed_cluster.test,
on terraform_plugin_test.tf line 26, in resource "azurerm_service_fabric_managed_cluster" "test":
26: resource …
```

poller: add `Created `as inprogress status for fabric managed

---

sdk/client/client.go
sdk/client/client_test.go
sdk/client/dataplane/client.go
sdk/client/dataplane/storage/client.go
sdk/client/interface.go

Add common methods to BaseClient interface to improve downstream interoperability with dataplane, msgraph and resourcemanager clients

Base client interoperability

---

sdk/client/client.go

Fixes a bug with Maintenance Delete where the response body is empty, but not nil, so this does not get unmarshalled.

sdk: check for empty response body before unmarshalling

---

sdk/client/resourcemanager/poller_lro.go

Fixes https://github.com/hashicorp/go-azure-sdk/issues/889

`sdk/client/resourcemanager` supporting `Patching` as a `provisioningState` value for NetApp

---

sdk/client/pollers/poller.go
sdk/client/resourcemanager/poller_lro.go

poller: retry LRO polling if 404 response received

---

sdk/client/client.go

Minor improvement, but adds a small amount of context mainly useful in the case that the API returns no error text.

enhancement: include HTTP status text in error when response is unexpected

---

sdk/client/client.go

Explicitly set three fields in the `retryablehttp.Client` struct.
`RetryWaitMin` is the shortest wait time before attempting to retry the request, and is the same as the default, but set explicitly here for clarity.
`RetryWaitMax` is the longest wait time before attempting to retry the request. The default is 30 seconds, we extend this to 61 second in consideration of potential API throttling for especially long-lasting eventual consistency issues.
With these values, the retry curve looks something [like this](https://go.dev/play/p/jlW1Lwc9VNT).
`RetryMax` is the maximum number of retries for a given API request, and is given the most consideration here. The default is 4, which is far too little for our purposes. Here, we set it to 16, which in conjunction with the above two field values, …

Extend retryablehttp limits in SDK base client

---

sdk/client/client.go

ref: https://github.com/manicminer/hamilton/pull/280

sdk/client: conditionally return the error when the resp is nil whilst retrying the request

---

sdk/auth/auth.go
sdk/auth/auth_test.go
sdk/auth/azure_cli_authorizer.go
sdk/auth/azure_cli_authorizer_test.go
sdk/auth/config.go
sdk/environments/interfaces.go
sdk/internal/azurecli/azcli.go
sdk/internal/test/environment_variables.go

Enables Azure CLI authentication to work in the case that multiple accounts are signed in, and each account has access to a subset of the available subscriptions. Currently, we pass the tenant ID to authenticate against which leaves Azure CLI with a decision to make as for which account to obtain an access token. Usually it will look at the default account (via `az account set`) and if this matches the tenant, it'll use that. If it doesn't match, it's forced to pick one of the accounts to use. Either of these choices may not align with the Terraform config, especially if it contains aliased providers using different subscriptions.
By passing the subscription ID, we inform it (when the API being authorized is Resource Manager) of the subscription we're going to be using, so it can make a …

auth: support subscription hint for Azure CLI, to help with multiple signed-in accounts with segregated access

---

sdk/client/msgraph/client.go
sdk/client/resourcemanager/client.go
sdk/nullable/nullable.go
sdk/nullable/nullable_test.go

* Add support for nullable model field types
* Make it possible to reuse clients by aligning the constructor function names
Required for https://github.com/hashicorp/pandora/pull/4346

refactor: improvements to support generated data plane SDKs

---

sdk/client/client.go

This PR modifies the logic about how the `client.RetryMax` is deduced. The main motivation is to avoid the retry exceeds the context dead line (if any).
This is useful for `terraform-provider-azurerm` users to get a useful error message instead of a useless "context deadline exceeded" error message, especially when doing a `terraform plan`, given all resources' read timeout is defined as 5min.
https://github.com/hashicorp/terraform-provider-azurerm/pull/21464
Given a storage account with PE correctly setup, while running in an errorneous network environment, that failed to resolve the storage blob data plane domain name. With this implementation, the retry log is as below:
```
2024-09-06T15:29:53.734+0800 [DEBUG] provider.terraform-provider-azurerm: [DEBUG] GET …
```

SDK: Adjust client RetryMax to not exceed timeout

---

sdk/client/client.go
sdk/go.mod

Users on unstable/unreliable networks can experience terraform operation disruption. Since the extendedRetryPolicy is needed only for Data Plane clients, this PR restores previous "Retry Forever" (specifically until operation context deadline expires) behaviour for Resource Manager  endpoints.
* bump go to `1.22`
* exclude azure management endpoints from network failure logic.

exclude Resource Manager endpoints from network failure detection

---

sdk/client/client.go

The `chaos` return an empty string in the `NextLink` property instead of set it to `null` when calling [`TargetTypes_List`
](https://github.com/Azure/azure-rest-api-specs/blob/8ad58020cfafc5ace71d85b31272acf4d6b694d3/specification/chaos/resource-manager/Microsoft.Chaos/stable/2023-11-01/targetTypes.json#L43C25-L43C41). It will make the provider wait endless...
I have opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/31098) on azure-rest-api-specs repo, but can we consider add this workaround to avoid similar bad cases?

handle empty `nextlink` value as end of pagination

---

sdk/client/resourcemanager/poller_provisioning_state.go

`ProvisioningStatePoller` - reverting removal of workaround for faux LRO early exit
