hashicorp/go-azure-sdk

README.md
docs/README.md
docs/authentication.md
docs/frequently-asked-questions.md

docs: adding the 'core' docs

---

sdk/environments/azure_gov.go

Fixes this comment: https://github.com/hashicorp/terraform-provider-azurerm/issues/20514#issuecomment-1434123991

sdk/environments: fixing the uri for Azure Gov

---

.github/workflows/pr-acceptance-tests.yml
sdk/auth/auth.go

Fix https://github.com/hashicorp/terraform-provider-azurerm/issues/20546

`auth` - Fix ODIC authentication failure

---

sdk/environments/environment.go
sdk/environments/interfaces.go

Related to https://github.com/hashicorp/terraform-provider-azurerm/pull/22400

Environments: add Available() method for APIs

---

sdk/client/resourcemanager/poller_lro.go

Fixes https://github.com/hashicorp/go-azure-sdk/issues/559

client/resourcemanager: handling Automation@2022-08-08 returning a 200 OK with no content

---

.github/workflows/automation-release.yaml

Fixes https://github.com/hashicorp/go-azure-sdk/actions/runs/6572655924/job/17854423465#step:6:12

github actions: threading the ssh auth socket through to the release job

---

scripts/update-azurerm-provider.sh

Fixes https://github.com/hashicorp/go-azure-sdk/actions/runs/6609501328/job/17949903076#step:6:60

automation: moving both the GHA and AzureRM paths up one level

---

.github/workflows/automation-release.yaml

The checkouts aren't reused, plus also fixing an issue where the description wouldn't be exported correctly

automation: updating the release script to checkout for the patcher step

---

scripts/update-azurerm-provider.sh

This differs from the usage in Pandora, but solves the issue, so fine.

automation: the email has to be escaped using single and not double quotes

---

scripts/update-azurerm-provider.sh

This should fix the invalid combination, which I suspect is coming from the tool in AzureRM

scripts: making the git config global

---

.github/workflows/automation-release.yaml

The other half of https://github.com/hashicorp/terraform-provider-azurerm/pull/23829

automation: setting the env vars needed for `update-go-azure-sdk`

---

.github/workflows/automation-release.yaml

This spans multiple lines, so base64-encoding this is a delightful workaround to allow us to pass this between stages
There is a size limit to the amount of data that can be passed, but it's unlikely to exceed 1MB so it's probably fine

automation: base64encoding/decoding the pr description

---

.github/workflows/automation-release.yaml
scripts/output-pr-description-for-gha.sh

Trying to workaround limitations in GHA

automation: outputting the values via a bash script

---

.github/workflows/automation-release.yaml

This needs to escape the command to be able to run successfully

automation: updating the command used to identify the PR Number

---

.github/workflows/automation-release.yaml

This should be `GH_TOKEN` and not `GITHUB_TOKEN`

automation: updating the env var name

---

.github/workflows/automation-release.yaml

This allows extra time if the other GHA takes a while

automation: retrying when getting the PR number from Github

---

sdk/client/resourcemanager/poller_lro.go

Fix the following acctest failure issue:

poller_lro: add pending status Pausing for anaylsisservices

---

sdk/client/resourcemanager/poller_lro.go

Fix the following acctest failure.

poller_lro: add pending status `CancelInProgress` for mysql

---

.github/workflows/automation-release.yaml
scripts/update-azurerm-provider.sh

Trying to make this more reproducible locally

automation: writing the result to a file

---

.github/workflows/automation-release.yaml

automation: adding the missing `run`

---

README.md

This is mostly to test the release process end-to-end, but it's also coming soon, so.

readme: adding the `microsoft-graph` link

---

GNUmakefile

Removing the entire directory removes the `go.mod` and README etc, so needs updating
Fixes https://github.com/hashicorp/pandora/pull/3702 and https://github.com/hashicorp/pandora/pull/3703

makefile: updating `prepare` to remove only directories

---

sdk/auth/azure_cli_authorizer.go
sdk/internal/azurecli/azcli.go

Tested manually on an Azure VM using system assigned and user assigned identities.
CLI output when signed in using system assigned managed identity:
```json
{
"environmentName": "AzureCloud",
"homeTenantId": "11111111-1111-1111-1111-111111111111",
"id": "77777777-7777-7777-7777-777777777777",
"isDefault": true,
"managedByTenants": [
{
"tenantId": "22222222-2222-2222-2222-222222222222"
},
{
"tenantId": "33333333-3333-3333-3333-333333333333"
}
],
"name": "Terraform Azure Providers",
"state": "Enabled",
"tenantId": "11111111-1111-1111-1111-111111111111",
"user": {
"assignedIdentityInfo": "MSI",
"name": "systemAssignedIdentity",
"type": "servicePrincipal"
}
}
```
CLI output when signed in using user assigned managed identity:
```json
{
"environmentName": "AzureCloud",
"homeTenantId": …
```

auth: omit tenant argument when acquiring tokens when authenticated using a managed identity

---

sdk/client/resourcemanager/poller.go
sdk/client/resourcemanager/poller_test.go

Some LROs are returning 200
https://github.com/Azure/azure-rest-api-specs/issues/27659
https://github.com/hashicorp/terraform-provider-azurerm/pull/25533

`sdk/client/resourcemanager` - create poller with status code 200 in response

---

sdk/client/client.go
sdk/client/dataplane/storage/client.go
sdk/client/dataplane/storage/errors.go
sdk/client/interface.go

- support for custom response error parsing in base client
- implement a custom response error parser for storage base client

feat: custom response error parsing
